### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/MI-000-SS00-000-js-create-an-api-with-express-URJy-_#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://shrouded-lake-59283.herokuapp.com/) and meets the following criteria:

- [x] Todos should have a field for the todo text and one to indicate whether or not the task has been completed
- [x] User should be able to see all todo items at `/todos`
- [x] POSTing to `/todos` should create a new todo item
- [x] Should be able to `GET`, `PUT`, and `DELETE` to `/todos/:id`
- [x] All requests and responses should be in JSON format
- [x] Should have a `.gitignore` file to keep unwanted files and folders from being tracked by git

**Comment by stuartpearman** [comment]
Nice work! :shipit: How long would you say this took you to complete?

**Comment by stuartpearman** [comment]
I just caught this, but it looks like you're not able to update whether a task has been completed using a `PUT` request.
